[PD] use call.request.queryParameters (#1648)
### Description

use `call.request.queryParameters` to properly fetch url query params
following the `?`

### Context

When testing with Sep24TestRoute on kubernetes, reference server throws
below error
```
16:39:37.446 INFO  - o.s.r.s.Sep24TestRoute - Called /sep24/interactive with parameters Parameters [transaction_id=[1ff8fcca-a5ca-4d2a-b883-723f8abe3b01]]
16:39:37.449 ERROR - o.s.r.ReferenceServer - Unexpected exception
org.stellar.reference.ClientException: Missing token parameter in the request
```
The potential cause could be proxy, encoding, middlewares or as simple
as this PR.

### Testing

- `./gradlew test`
- Printed out in local that params were correctly parsed.