[ANCHOR-943] Improve assets config error msg (#1665)
### Description

New error will be in fomat like below:

***************************
APPLICATION FAILED TO START
***************************

Description:

```
Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'assets' to org.stellar.anchor.config.AssetsConfig failed:

    Reason: Cannot read from asset file: /Users/jiahuihu/Documents/GitHub/anchor-platform/service-runner/out/production/resources/config/assets.yaml.
Error: Asset stellar:USDC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP: SEP-6 deposit 'max_amount' must be positive (current value: -1).
Asset stellar:USDC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP: SEP-24 requires at least one withdrawal method.
Asset stellar:USDC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP: SEP-24 withdraw 'max_amount' must be positive (current value: -1).
Asset stellar:USDC:GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5: SEP-24 duplicate deposit method found: SWIFT.
Asset stellar:USDC:GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5: SEP-31 'quotes_supported' must be true if 'quotes_required' is true, .
Asset stellar:JPYC:GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP: SEP-31 receive 'min_amount' must be non-negative (current value: -1).
Asset iso4217:USD: SEP-38 invalid country code 'USA'. Must be a valid 2-letter ISO country code.
Asset iso4217:CAD: SEP-38 sell delivery method description cannot be empty.


Action:

Update your application's configuration
```

### Context

Previsous error msg were vage and not instructive

### Testing

- `./gradlew test`